
Id CommandLine                                                                                                                                                                                                           
-- -----------                                                                                                                                                                                                           
 1 . 'F:\Program Files\Microsoft\Exchange Server\V15\bin\RemoteExchange.ps1'; Connect-ExchangeServer -auto -ClientApplication:ManagementShell                                                                            
 2 Get-MessageTrackingLog -Recipients user@example.com -Start "mm/dd/yyyy hh:mm am/pm" -End "mm/dd/yyyy hh:mm am/pm" | ft Timestamp, Source, EventId, MessageSubject, Sender, Recipients -AutoSize                       
 3 Get-MessageTrackingLog -Recipients novatest@ambico.caom                                                                                                                                                               
 4 Get-MessageTrackingLog -Recipients novatest@ambico.com                                                                                                                                                                
 5 Get-Queue | ft Identity, MessageCount, Status, LastError -AutoSize                                                                                                                                                    
 6 Get-MessageTrackingLog -Recipients novatest@ambico.com                                                                                                                                                                
 7 Get-MessageTrackingLog -Recipients novatest@ambico.com                                                                                                                                                                
 8 Get-MessageTrackingLog -Recipients novatest@ambico.com                                                                                                                                                                
 9 Get-MessageTrackingLog -Recipients novatest@ambico.com                                                                                                                                                                
10 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
11 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com | select eventID                                                                                                                                          
12 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
13 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
14 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
15 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
16 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
17 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
18 Get-Queue | ft Identity, MessageCount, Status, LastError -AutoSize                                                                                                                                                    
19 Get-Message -Queue "queue_identity_from_previous_step" | ft FromAddress, Status, MessageSubject, LastError -AutoSize                                                                                                  
20 Get-Message -Queue "Ambico-Mail\19506" | ft FromAddress, Status, MessageSubject, LastError -AutoSize                                                                                                                  
21 Get-ReceiveConnector | ft Name, Bindings, RemoteIPRanges -AutoSize                                                                                                                                                    
22 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
23 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
24 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotAfter,Services                                                                                                                                            
25 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
26 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotAfter,Services                                                                                                                                            
27 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
28 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotAfter,Services                                                                                                                                            
29 cd c:\code                                                                                                                                                                                                            
30 ls                                                                                                                                                                                                                    
31 .\Backup-RemoveOldExhangeCerts.ps1                                                                                                                                                                                    
32 .\Backup-RemoveOldExhangeCerts2.ps1                                                                                                                                                                                   
33 .\Backup-RemoveOldExhangeCerts3.ps1                                                                                                                                                                                   
34 Get-ExchangeCertificate                                                                                                                                                                                               
35 .\Backup-RemoveOldExhangeCerts3.ps1                                                                                                                                                                                   
36 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
37 .\Backup-RemoveOldExhangeCerts4.ps1                                                                                                                                                                                   
38 .\Backup-RemoveOldExhangeCerts5.ps1                                                                                                                                                                                   
39 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotAfter,Services                                                                                                                                            
40 Get-ExchangeCertificate | select * | export-csv c:\code\exchangecerts_Aug_03_2023.csv                                                                                                                                 
41 # Thumbprint of the certificate                                                                                                                                                                                       
42 $thumbprint = "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"                                                                                                                                                              
43 # Retrieve the certificate details                                                                                                                                                                                    
44 $certificate = Get-ExchangeCertificate -Thumbprint $thumbprint                                                                                                                                                        
45 # Check if the certificate is enabled for SMTP                                                                                                                                                                        
46 if ($certificate.Services -like "*SMTP*") {...                                                                                                                                                                        
47 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotBefore,NotAfter,Services,IsSelfSigned,CertificateDomains                                                                                                  
48 ls                                                                                                                                                                                                                    
49 .\RemoveOldExhangeCerts1.ps1                                                                                                                                                                                          
50 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotBefore,NotAfter,Services,IsSelfSigned,CertificateDomains                                                                                                  
51 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" | Format-List TlsCertificateName                                                                                                    
52 Get-ExchangeCertificate | Format-List Thumbprint,Subject,NotBefore,NotAfter,Services,IsSelfSigned,CertificateDomains,issuer                                                                                           
53 Set-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" -TlsCertificateName "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"                                                                      
54 # Retrieve certificate details using thumbprint                                                                                                                                                                       
55 $TLSCert = Get-ExchangeCertificate -Thumbprint "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"                                                                                                                             
56 # Form the string using Issuer and Subject                                                                                                                                                                            
57 $TLSCertName = "<I>$($TLSCert.Issuer)<S>$($TLSCert.Subject)"                                                                                                                                                          
58 # Set the TlsCertificateName on the Send Connector                                                                                                                                                                    
59 Set-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" -TlsCertificateName $TLSCertName                                                                                                    
60 .\RemoveOldExhangeCerts1.ps1                                                                                                                                                                                          
61 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" | Format-List Name, TlsCertificateName                                                                                              
62 # Get the certificate details using the thumbprint of the valid certificate                                                                                                                                           
63 $thumbprint = "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"                                                                                                                                                              
64 $certificate = Get-ExchangeCertificate -Thumbprint $thumbprint                                                                                                                                                        
65 # Prepare the TlsCertificateName value using the issuer and subject from the certificate                                                                                                                              
66 $TlsCertName = "<I>$($certificate.Issuer)<S>$($certificate.Subject)"                                                                                                                                                  
67 # Get the Send connector you want to modify                                                                                                                                                                           
68 $connectorName = "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744"                                                                                                                                      
69 $sendConnector = Get-SendConnector -Identity $connectorName                                                                                                                                                           
70 # Set the TlsCertificateName property of the Send connector to the new certificate                                                                                                                                    
71 Set-SendConnector -Identity $sendConnector.Identity -TlsCertificateName $TlsCertName                                                                                                                                  
72 # Get the certificate details using the thumbprint of the valid certificate                                                                                                                                           
73 $thumbprint = "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"                                                                                                                                                              
74 $certificate = Get-ExchangeCertificate -Thumbprint $thumbprint                                                                                                                                                        
75 # Prepare the TlsCertificateName value using the issuer and subject from the certificate                                                                                                                              
76 $TlsCertName = "<I>$($certificate.Issuer)<S>$($certificate.Subject)"                                                                                                                                                  
77 # Get the Send connector you want to modify                                                                                                                                                                           
78 $connectorName = "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744"                                                                                                                                      
79 $sendConnector = Get-SendConnector -Identity $connectorName                                                                                                                                                           
80 # Set the TlsCertificateName property of the Send connector to the new certificate                                                                                                                                    
81 Set-SendConnector -Identity $sendConnector.Identity -TlsCertificateName $TlsCertName                                                                                                                                  
82 # Get the certificate details using the thumbprint of the valid certificate                                                                                                                                           
83 $thumbprint = "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"                                                                                                                                                              
84 $certificate = Get-ExchangeCertificate -Thumbprint $thumbprint                                                                                                                                                        
85 # Prepare the TlsCertificateName value using the issuer and subject from the certificate                                                                                                                              
86 $TlsCertName = "<I>$($certificate.Issuer)<S>$($certificate.Subject)"                                                                                                                                                  
87 # Get the Send connector you want to modify                                                                                                                                                                           
88 $connectorName = "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744"                                                                                                                                      
89 $sendConnector = Get-SendConnector -Identity $connectorName                                                                                                                                                           
90 # Set the TlsCertificateName property of the Send connector to the new certificate                                                                                                                                    
91 Set-SendConnector -Identity $sendConnector.Identity -TlsCertificateName $TlsCertName                                                                                                                                  
92 $validCert = Get-ExchangeCertificate | Where-Object {$_.Thumbprint -eq "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"}                                                                                                    
93 $certName = "<I>$($validCert.Issuer)<S>$($validCert.Subject)"                                                                                                                                                         
94 Set-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" -TlsCertificateName $certName                                                                                                       
95 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" | Format-List Name, TlsCertificateName                                                                                              
96 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744"                                                                                                                                     
97 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" | select *                                                                                                                          
98 ls                                                                                                                                                                                                                    
99 .\RemoveOldExhangeCerts1.ps1                                                                                                                                                                                          
100 $newCert = Get-ExchangeCertificate | Where-Object {$_.Thumbprint -eq "7FD683C1D53F595B33BD4FC8A87497EB2E659CEA"}                                                                                                      
101 $TLSCertName = "<I>" + $newCert.Issuer + "<S>" + $newCert.Subject                                                                                                                                                     
102 Set-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" -TlsCertificateName $TLSCertName                                                                                                    
103 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" | Format-List *                                                                                                                     
104 Remove-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744"                                                                                                                                  
105 Get-SendConnector "Outbound to Office 365 - 184c8e2f-b4ef-4a58-8e56-1ef196f9b744" | Format-List *                                                                                                                     
106 Get-ReceiveConnector | Format-List NameTlsCertificateName                                                                                                                                                           
107 Get-ExchangeCertificate | Format-List Thumbprint, Subject, NotAfter, Services                                                                                                                                         
108 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
109 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
110 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
111 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
112 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
113 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
114 Get-Queue                                                                                                                                                                                                             
115 Get-MessageTrackingLog -Sender "aollivierre@novanetworks.com" -Start (Get-Date).AddDays(-30) -End (Get-Date) | Format-List Timestamp, EventId, Source, Sender, Recipients, MessageSubject, MessageInfo, ClientIp, S...
116 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
117 Get-MessageTrackingLog -Sender "aollivierre@novanetworks.com" -Start (Get-Date).AddDays(-30) -End (Get-Date) | Format-List Timestamp, EventId, Source, Sender, Recipients, MessageSubject, MessageInfo, ClientIp, S...
118 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
119 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
120 Get-RemoteMailbox                                                                                                                                                                                                     
121 Get-mailbox                                                                                                                                                                                                           
122 Get-RemoteMailbox                                                                                                                                                                                                     
123 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
124 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
125 Get-OwaVirtualDirectory | fl server, name, externalurl                                                                                                                                                                
126 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com                                                                                                                                                           
127 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com | ...                                                                                                                                                     
128 Get-MessageTrackingLog -Sender aollivierre@novanetworks.com | Select-Object Timestamp, EventId, Source, Recipients, MessageSubject | Sort-Object Timestamp | Format-Table -AutoSize                                   
129 8/4/2023 1:29:23 AM  HAREDIRECTFAIL SMTP        {NovaTest@ambico.com}    test #16 from nova to ambico onprem aug 1:27 AM EST after changing mx to on prem exchange email.ambico.com                                   
130 8/4/2023 1:29:23 AM  RECEIVE        SMTP        {NovaTest@ambico.com}    test #16 from nova to ambico onprem aug 1:27 AM EST after changing mx to on prem exchange email.ambico.com                                   
131 8/4/2023 1:29:35 AM  AGENTINFO      AGENT       {NovaTest@ambico.com}    test #16 from nova to ambico onprem aug 1:27 AM EST after changing mx to on prem exchange email.ambico.com                                   
132 8/4/2023 1:29:35 AM  DELIVER        STOREDRIVER {NovaTest@ambico.com}    test #16 from nova to ambico onprem aug 1:27 AM EST after changing mx to on prem exchange email.ambico.com                                   
133 Get-DatabaseAvailabilityGroup                                                                                                                                                                                         
134 Get-DatabaseAvailabilityGroup                                                                                                                                                                                         
135 Get-ExchangeServer | Where-Object { $_.ServerRole -like "*Mailbox*" } | ForEach-Object { [PSCustomObject]@{ ServerName = $_.Name; DAG = $_.DatabaseAvailabilityGroup } } | Format-Table -AutoSize                     
136 Get-MailboxDatabase -Server "YourServerName"                                                                                                                                                                          
137 Get-MailboxDatabase -Server "AMBICO-MAIL"                                                                                                                                                                             
138 Get-History                                                                                                                                                                                                           


