# Import required module for HTML reporting
Import-Module PSWriteHTML -ErrorAction Stop

function Write-OperationLog {
    param(
        [Parameter(Mandatory)]
        [string]$Message,
        
        [ValidateSet('Info', 'Warning', 'Error')]
        [string]$Level = 'Info'
    )
    
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $logMessage = "[$timestamp] [$Level] $Message"
    
    switch ($Level) {
        'Info' { Write-Host $logMessage -ForegroundColor Green }
        'Warning' { Write-Host $logMessage -ForegroundColor Yellow }
        'Error' { Write-Host $logMessage -ForegroundColor Red }
    }
}

function Connect-ExchangeOnlineWithCheck {
    [CmdletBinding()]
    param()
    
    Write-OperationLog "Checking Exchange Online connection..."
    
    $exchangeSession = Get-PSSession | Where-Object { 
        $_.ConfigurationName -eq 'Microsoft.Exchange' -and $_.State -eq 'Opened' 
    }
    
    if (-not $exchangeSession) {
        Write-OperationLog "No active Exchange Online session found. Connecting..." -Level Warning
        Connect-ExchangeOnline
        Write-OperationLog "Successfully connected to Exchange Online" -Level Info
    }
    else {
        Write-OperationLog "Active Exchange Online session found" -Level Info
    }
}

function Enable-MailboxArchive {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [string]$MailboxIdentity
    )

    try {
        $mailbox = Get-Mailbox -Identity $MailboxIdentity -ErrorAction Stop
        
        if ($mailbox.ArchiveStatus -eq "Active") {
            Write-OperationLog "Archive already enabled for $MailboxIdentity" -Level Warning
            return [PSCustomObject]@{
                Mailbox = $MailboxIdentity
                Status = "Already Enabled"
                ArchiveStatus = $mailbox.ArchiveStatus
                Error = $null
            }
        }

        Enable-Mailbox -Identity $MailboxIdentity -Archive -ErrorAction Stop
        Start-Sleep -Seconds 2  # Brief pause to allow for backend processing
        
        $updatedMailbox = Get-Mailbox -Identity $MailboxIdentity
        $status = if ($updatedMailbox.ArchiveStatus -eq "Active") { "Enabled" } else { "Failed" }
        
        Write-OperationLog "Archive $status for $MailboxIdentity" -Level Info
        
        return [PSCustomObject]@{
            Mailbox = $MailboxIdentity
            Status = $status
            ArchiveStatus = $updatedMailbox.ArchiveStatus
            Error = $null
        }
    }
    catch {
        Write-OperationLog "Failed to enable archive for $MailboxIdentity : $_" -Level Error
        return [PSCustomObject]@{
            Mailbox = $MailboxIdentity
            Status = "Failed"
            ArchiveStatus = "Error"
            Error = $_.Exception.Message
        }
    }
}

function Export-ArchiveReport {
    param (
        [Parameter(Mandatory)]
        [array]$Results,
        [Parameter(Mandatory)]
        [string]$OutputPath
    )
    
    # Calculate metadata
    $metadata = @{
        GeneratedBy = $env:USERNAME
        GeneratedOn = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        TotalMailboxes = $Results.Count
        EnabledCount = ($Results | Where-Object Status -eq "Enabled").Count
        AlreadyEnabledCount = ($Results | Where-Object Status -eq "Already Enabled").Count
        FailedCount = ($Results | Where-Object Status -eq "Failed").Count
    }

    # Clean up the results for display
    $cleanResults = $Results | Select-Object @{
        Name = 'Mailbox'
        Expression = {$_.Mailbox}
    }, @{
        Name = 'Status'
        Expression = {$_.Status}
    }, @{
        Name = 'Archive Status'
        Expression = {$_.ArchiveStatus}
    }, @{
        Name = 'Error Details'
        Expression = {if ($_.Error) { $_.Error } else { '-' }}
    }

    $reportParams = @{
        FilePath = $OutputPath
        ShowHTML = $true
        Title = "Online Archive Enablement Report"
    }

    New-HTML @reportParams {
        New-HTMLSection -HeaderText "Operation Summary" {
            New-HTMLPanel {
                New-HTMLText -Text @"
                <h3>Report Details</h3>
                <ul>
                    <li>Generated By: $($metadata.GeneratedBy)</li>
                    <li>Generated On: $($metadata.GeneratedOn)</li>
                    <li>Total Mailboxes Processed: $($metadata.TotalMailboxes)</li>
                    <li>Newly Enabled: $($metadata.EnabledCount)</li>
                    <li>Already Enabled: $($metadata.AlreadyEnabledCount)</li>
                    <li>Failed Operations: $($metadata.FailedCount)</li>
                </ul>
"@
            }
        }
        
        New-HTMLSection -HeaderText "Archive Enablement Results" {
            New-HTMLTable -DataTable $cleanResults -ScrollX -Buttons @('copyHtml5', 'excelHtml5', 'csvHtml5') -SearchBuilder {
                New-TableCondition -Name 'Status' -ComparisonType string -Operator eq -Value 'Failed' -BackgroundColor Salmon -Color Black
                New-TableCondition -Name 'Status' -ComparisonType string -Operator eq -Value 'Enabled' -BackgroundColor LightGreen -Color Black
                New-TableCondition -Name 'Status' -ComparisonType string -Operator eq -Value 'Already Enabled' -BackgroundColor LightBlue -Color Black
            }
        }
    }
}

# Main execution
$mailboxes = @(
    "cc@tunngavik.com",
    "epo@tunngavik.com",
    "hrclerk@tunngavik.com",
    "Invoices@tunngavik.com",
    "payroll@tunngavik.com",
    "relief@tunngavik.com",
    "ri-support@tunngavik.com"
)

$outputDir = Join-Path $PSScriptRoot "ArchiveReports_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

# Connect to Exchange Online
Connect-ExchangeOnlineWithCheck

# Process mailboxes
$results = [System.Collections.Generic.List[object]]::new()

foreach ($mailbox in $mailboxes) {
    $result = Enable-MailboxArchive -MailboxIdentity $mailbox
    $results.Add($result)
}

# Export results
$csvPath = Join-Path $outputDir "archive_results.csv"
$htmlPath = Join-Path $outputDir "archive_report.html"

$results | Export-Csv -Path $csvPath -NoTypeInformation
Export-ArchiveReport -Results $results -OutputPath $htmlPath

Write-OperationLog "Results exported to: $outputDir"