# Load required modules
Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
Import-Module PSWriteHTML

function Search-EmailTrace {
    param(
        [Parameter(Mandatory=$true)]
        [string]$EmailAddress,
        
        [Parameter(Mandatory=$false)]
        [DateTime]$StartDate = (Get-Date).AddDays(-1),
        
        [Parameter(Mandatory=$false)]
        [DateTime]$EndDate = (Get-Date)
    )
    
    $results = Get-MessageTrackingLog -Start $StartDate -End $EndDate -ResultSize Unlimited -Recipients $EmailAddress |
        Select-Object Timestamp,
                      EventId,
                      Source,
                      MessageSubject,
                      Sender,
                      @{Name='Recipients';Expression={$_.Recipients}},
                      ClientHostname,
                      ServerHostname,
                      SourceContext,
                      ConnectorId,
                      MessageId
                      
    return $results
}

function Export-EmailTraceReport {
    param(
        $Results,
        $OutputDir,
        $Metadata
    )
    
    $htmlPath = Join-Path $OutputDir "EmailTraceReport.html"
    
    New-HTML -Title "Exchange Email Trace Report" -FilePath $htmlPath -ShowHTML {
        New-HTMLSection -HeaderText "Trace Summary" {
            New-HTMLPanel {
                New-HTMLText -Text @"
                <h3>Search Parameters</h3>
                <ul>
                    <li>Email Address: $($Metadata.EmailAddress)</li>
                    <li>Start Date: $($Metadata.StartDate)</li>
                    <li>End Date: $($Metadata.EndDate)</li>
                    <li>Generated By: $($Metadata.GeneratedBy)</li>
                    <li>Generated On: $($Metadata.GeneratedOn)</li>
                </ul>
"@
            }
        }
        
        New-HTMLSection -HeaderText "Message Tracking Results" {
            New-HTMLTable -DataTable $Results -ScrollX -Buttons @('copyHtml5', 'excelHtml5', 'csvHtml5') {
                New-TableCondition -Name 'EventId' -ComparisonType 'string' -Operator 'eq' -Value 'FAIL' -BackgroundColor '#ffcdd2' -Color '#000000'
                New-TableCondition -Name 'EventId' -ComparisonType 'string' -Operator 'eq' -Value 'DELIVER' -BackgroundColor '#c8e6c9' -Color '#000000'
            }
        }
    }
}

# Main execution block
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$outputDir = Join-Path $PSScriptRoot "EmailTrace_$timestamp"
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

# Example usage
$emailAddress = "support@novanetworks.com"
$startDate = (Get-Date).AddDays(-1)
$endDate = Get-Date

$metadata = @{
    EmailAddress = $emailAddress
    StartDate = $startDate
    EndDate = $endDate
    GeneratedBy = $env:USERNAME
    GeneratedOn = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
}

$results = Search-EmailTrace -EmailAddress $emailAddress -StartDate $startDate -EndDate $endDate

# Export reports
$results | Export-Csv -Path (Join-Path $outputDir "email_trace_results.csv") -NoTypeInformation
Export-EmailTraceReport -Results $results -OutputDir $outputDir -Metadata $metadata